api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView
)
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.urls import include
from api.projects import views as api_projects_views
from api.users import views as api_users_views



urlpatterns = [
    path('projects/', api_projects_views.ProjectsApiView.as_view(), name="projects_api"),
    path('projects/<str:pk>/', api_projects_views.ProjectCrudApiView.as_view(), name="project_crud_api"),
    path('projects/<str:pk>/review/', api_projects_views.ReviewProjectApiView.as_view(), name="review_project_api"),
    path('projects/<str:pk>/review/<str:id>/', api_projects_views.UpdateReviewProjectView.as_view(), name="update_review_project_api"),

    path('users/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('users/register/', api_users_views.UserRegistrationApiView.as_view(), name="register_user_api"),
    path('users/logout/', api_users_views.LogoutApiView.as_view(), name='logout_api'),
    path('users/password-reset/', include('django_rest_passwordreset.urls', namespace="password_reset")),

    path('profiles/', api_users_views.ListProfilesApiView.as_view(), name='profiles_api'),  # Used only to return profiles list, the creation of a profile is made automatically when a user is registered
    path('profiles/<str:pk>/', api_users_views.ProfileApiView.as_view(), name='single_profile_api'),
    path('profiles/<str:pk>/skills/', api_users_views.ProfileSkillsApiView.as_view(), name="profile_skills_api"),  # Return and create skills of the authenticated profile
    path('profiles/<str:pk>/skills/<str:id>/', api_users_views.ProfileSkillRUDApiView.as_view(), name="profile_skill_rud_api"),
    path('profiles/<str:pk>/messages/', api_users_views.MessagesApiView.as_view(), name="profile_messages_api"),
    path('profiles/<str:pk>/messages/<str:id>', api_users_views.SingleMessageApiView.as_view(), name="profile_single_message_api"),
    path('sent-message/<str:pk>/', api_users_views.SendMessageApiView.as_view(), name="sent_message_api"),

    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger_ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc')
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>', views.user_profile, name='user_profile'),
    path('login/', views.login_user, name='login_page'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('my-account/', views.user_account, name='my_account'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('add-skill/', views.add_skill, name='add_skill'),
    path('edit-skill/<str:pk>', views.edit_skill, name='edit_skill'),
    path('delete-skill/<str:pk>', views.delete_skill, name='delete_skill'),
    path('inbox', views.inbox, name='inbox'),
    path('read-message/<str:pk>', views.read_message, name='read_message'),
    path('send-message/<str:pk>', views.send_message, name='send_message')
]

projects/models.py
# Django imports
from django.db import models
# Local imports
from users.models import Profile
# Third party imports
from cloudinary.models import CloudinaryField
import uuid


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name    


class Project(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = CloudinaryField(null=True, blank=True)
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        ordering = ['-vote_ratio', '-vote_total', '-created']

    def __str__(self):
        return self.title

    @property
    def get_votes_total(self):
        reviews = self.review_set.all()
        upvotes = reviews.filter(value='up').count()
        self.vote_total = reviews.count()
        self.vote_ratio = (upvotes / self.vote_total) * 100
        self.save()

    @property
    def reviewers_list(self):
        reviewers_id = self.review_set.all().values_list('owner__id', flat=True)
        return reviewers_id

    @property
    def get_image_url(self):
        try:
            image_url = self.featured_image.url
        except:
            image_url = ''
        return image_url
    


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        unique_together = [['owner', 'project'] ]

    def __str__(self):
        return self.value

users/models.py
# Django imports
from django.db import models
from django.conf import settings
from django.templatetags.static import static
# Third party imports
import uuid
from cloudinary.models import CloudinaryField


# Create your models here.
class ProfileQuerySet(models.QuerySet):
    def get_profiles_by_skills(self, query):
        skills = Skill.objects.filter(name__icontains=query)
        return self.filter(skill__in=skills).distinct()


class Profile(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = CloudinaryField("Profile image", null=True, blank=True)
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    personal_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileQuerySet.as_manager()

    def __str__(self):
        return str(self.user.username)

    @property
    def get_image_url(self):
        if self.profile_image:
            return self.profile_image.url
        return static("images/no-user-image.png")


class Skill(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="recipient_messages")
    sender_name = models.CharField(max_length=200, null=True, blank=True)
    sender_email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', 'created']

    def save(self, *args, **kwargs):
        self.sender_name = self.sender.name
        self.sender_email = self.sender.email 
        return super().save(*args, **kwargs)

users/views.py
from django.http import Http404
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models.aggregates import Count
from .utils import search_profiles, paginate_profiles
from .models import Profile, Skill
from projects.models import Tag
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, SendMessageForm


# Create your views here.
def profiles(request):
    if request.GET.get('search'):
        profiles, query = search_profiles(request)
    else:
        query = ''
        profiles = Profile.objects.all().exclude(profile_image='').annotate(projects_number=Count('project')).order_by('-projects_number')
    profiles, custom_range = paginate_profiles(request, profiles, 3)
    context = {
        'profiles': profiles,
        'query': query,
        'pagination_range': custom_range
    }
    return render(request, 'users/profiles.html', context)


def user_profile(request, pk):
    profile = Profile.objects.filter(id=pk).first()
    main_skills = profile.skill_set.exclude(description="")
    other_skills = profile.skill_set.filter(description="")
    context = {
        'profile': profile,
        'main_skills': main_skills,
        'other_skills': other_skills
    }
    return render(request, "users/user-profile.html", context)


def login_user(request):
    
    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == "POST":
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
        user = User.objects.filter(username__iexact=username).first()
        if user:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(request.GET['next'] if 'next' in request.GET else 'my_account')
            else:
                messages.error(request, "Username or password incorrect")
        else:
             messages.error(request, "User doesn't exist")

    context = {
        'page': 'login'
    }
    return render(request, "users/login-register.html", context)


@login_required(login_url='login_page')
def logout_user(request):
    logout(request)
    messages.info(request, "User was logged out")
    return redirect('login_page')


def register_user(request):
    if request.user.is_authenticated:
        return redirect('my_account')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, "Your account was successfully created!")
            login(request, user)
            return redirect('my_account')
        else:
            context = {
                'page': 'register',
                'form': form
            }
            messages.error(request, "There was an error when registering the user, check all fields are filled correctly")
            return render(request, 'users/login-register.html', context)
    else:
        context = {
            'page': 'register',
            'form': CustomUserCreationForm()
        }
        return render(request, 'users/login-register.html', context)


@login_required(login_url='login_page')
def user_account(request):
    profile = request.user.profile
    context = {
        'profile': profile
    }
    return render(request, 'users/account.html', context)


@login_required(login_url='login_page')
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('my_account')
    form = ProfileForm(instance=request.user.profile)
    context = {
        'form': form
    }
    return render(request, 'users/profile-form.html', context)


@login_required(login_url='login_page')
def add_skill(request):
    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = request.user.profile
            skill.name = skill.name.upper()
            skill.save()
            Tag.objects.get_or_create(name=skill.name)  # Creating a tag for the skill if doesn't exist one to reflect it when creating a project
            messages.success(request, "Skill was added successfully!")
            return redirect('my_account')
        else:
            context = {
                'form': form
            }
            messages.error("There was an error adding your skill, please try again")
            return render(request, 'users/add-skill-form.html', context)
    else:
        form = SkillForm()
        context = {
            'form': form
        }
        return render(request, 'users/add-skill-form.html', context)


@login_required(login_url='login_page')
def edit_skill(request, pk):
    skill = Skill.objects.filter(id=pk).first()
    if skill.owner == request.user.profile:
        if request.method == 'POST':
            form = SkillForm(request.POST, instance=skill)
            if form.is_valid():
                skill = form.save(commit=False)
                skill.owner = request.user.profile
                skill.name = skill.name.upper()
                skill.save()
                Tag.objects.get_or_create(name=skill.name)  # Creating a tag for the skill if doesn't exist one to reflect it when creating a project
                messages.success(request, "Skill was updated successfully!")
                return redirect('my_account')
            else:
                context = {
                    'form': form
                }
                messages.error(request, "There was an error updating your skill, please try again")
                return render(request, 'users/add-skill-form.html', context)
        else:
            form = SkillForm(instance=skill)
            context = {
                'form': form
            }
            return render(request, 'users/add-skill-form.html', context)
    else:
        return redirect('my_account')


@login_required(login_url='login_page')
def delete_skill(request, pk):
    skill = Skill.objects.filter(id=pk).first()
    if skill.owner == request.user.profile:
        if request.method == 'POST':
            skill.delete()
            messages.success(request, "The skill was deleted successfully")
            return redirect('my_account')
        else:
            context = {
                'object': skill
            }
            return render(request, 'delete-template.html', context)


@login_required(login_url='login_page')
def inbox(request):
    profile = request.user.profile
    recieved_messages = profile.recipient_messages.all()
    new_messages = recieved_messages.filter(is_read=False).count()
    context = {
        'recieved_messages': recieved_messages,
        'new_messages': new_messages
    }
    return render(request, 'users/inbox.html', context)


@login_required(login_url='login_page')
def read_message(request, pk):
    profile = request.user.profile
    try:
        message = profile.recipient_messages.get(id=pk)
        if not message.is_read:
            message.is_read = True
            message.save()
        context = {
        'message': message
    }
    except:
        return redirect('inbox')
    return render(request, 'users/message.html', context)


@login_required(login_url='login_page')
def send_message(request, pk):
    message_receiver = Profile.objects.get(id=pk)
    if request.method == 'POST':
        send_message_form = SendMessageForm(request.POST)
        if send_message_form.is_valid():
            message_instance = send_message_form.save(commit=False)
            message_instance.sender = request.user.profile
            message_instance.recipient = message_receiver
            message_instance.save()
            messages.success(request, "Your message has been sent")
            return redirect('user_profile', pk=pk)
    if str(request.user.profile.id) == str(pk):
        return redirect('user_profile', pk=pk)
    else:
        send_message_form = SendMessageForm()
        context = {
            'send_message_form': send_message_form,
            'message_receiver_profile': message_receiver
        }
        return render(request, 'users/send-message-form.html', context)

users/templates/users/account.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit_profile' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{ profile.get_image_url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              {% if profile.short_intro %}
              <p class="dev__title">{{ profile.short_intro }}</p>{% endif %}
              {% if profile.location %}
              <p class="dev__location">Based in {{ profile.location }}</p>
              {% endif %}
              <ul class="dev__social">
                {% if profile.social_github %}
                        <li>
                          <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                        </li>
                    {% endif %}
                    {% if profile.social_twitter %}
                        <li>
                          <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="im im-twitter"></i></a>
                        </li>
                    {% endif %}
                    {% if profile.social_linkedin %}
                        <li>
                          <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                        </li>
                    {% endif %}
                    {% if profile.personal_website %}
                        <li>
                          <a title="Personal Website" href="{{ profile.personal_website }}" target="_blank"><i class="im im-globe"></i></a>
                        </li>
                    {% endif %}
              </ul>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio|linebreaks }}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'add_skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in profile.skill_set.all %}
              <tr>
                <td class="settings__tableInfo">
                  <h4>{{ skill.name }}</h4>
                  <p>
                    {{ skill.description }}
                  </p>
                </td>
                <td class="settings__tableActions">
                  <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit_skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                  <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_skill' skill.id %}?next=/my-account"><i class="im im-x-mark-circle-o"></i>
                    Delete</a>
                </td>
              </tr>
            {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create_project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for project in profile.project_set.all %}
              <tr>
                <td class="settings__thumbnail">
                  <a href="{% url 'single_project' project.id %}"><img src="{{ project.get_image_url }}" alt="Project Thumbnail" /></a>
                </td>
                <td class="settings__tableInfo">
                  <a href="{% url 'single_project' project.id %}">{{ project.title }}</a>
                  <p>
                    {{ project.description|linebreaks|slice:"150" }}
                  </p>
                </td>
                <td class="settings__tableActions">
                  <a class="tag tag--pill tag--main settings__btn" href="{% url 'update_project' project.id %}"><i class="im im-edit"></i> Edit</a>
                  <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_project' project.id %}?next=/my-account"><i class="im im-x-mark-circle-o"></i>
                    Delete</a>
                </td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

users/templates/users/add-skill-form.html
{% extends "main.html" %}

{% block content %}
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'my_account' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form__field">
                    <label for="formInput{{ field.label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit"/>
            </form>
        </div>
    </div>
</main>
{% endblock content %}

users/templates/users/inbox.html
{% extends "main.html" %}

{% block content %}
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{ new_messages }}</span>)</h3>
    {% if recieved_messages %}
    <ul class="messages">
      {% for message in recieved_messages %}
        <li class="message{% if not message.is_read %} message--unread{% endif %}">
          <a href="{% url 'read_message' message.id %}">
            <span class="message__author">{{ message.sender_name }}</span>
            <span class="message__subject">{{ message.subject }}</span>
            <span class="message__date">{{ message.created }}</span>
          </a>
        </li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
</main>
{% endblock content %}

users/templates/users/message.html
{% extends "main.html" %}

{% block content %}
<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
      <h2 class="message__subject">{{ message.subject }}</h4>
        <a href="{% url 'user_profile' message.sender.id %}" class="message__author">{{ message.sender.name }}</a>
        <p class="message__date">{{ message.created }}</p>
        <div class="message__body">
          {{ message.body }}
        </div>
    </div>
  </div>
</main>
{% endblock content %}

users/templates/users/profile-form.html
{% extends 'main.html' %}

{% block content %}
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'my_account' %}"><i class="im im-angle-left"></i></a>
            <br>
            <form class="form" method="POST" action="{% url 'edit_profile' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Input:Text -->
                {% for field in form %}
                    <div class="form__field">
                        <label for="formInput{{ field.label }}">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit info" />
            </form>
        </div>
    </div>
</main>
{% endblock content%}

users/templates/users/user-profile.html
{% extends "main.html" %}

{% block content %}
<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
            <div class="card text-center">
                <div class="card__body dev">
                <img class="avatar avatar--xl" src="{{ profile.get_image_url }}" />
                <h2 class="dev__name">{{ profile.name }}</h2>
                {% if profile.short_intro %}
                    <p class="dev__title">{{ profile.short_intro }}</p>
                {% endif %}
                {% if profile.location %}
                    <p class="dev__location">Based in {{ profile.location }}</p>
                {% endif %}
                <ul class="dev__social">
                    {% if profile.social_github %}
                        <li>
                        <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                        </li>
                    {% endif %}
                    {% if profile.social_twitter %}
                        <li>
                        <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="im im-twitter"></i></a>
                        </li>
                    {% endif %}
                    {% if profile.social_linkedin %}
                        <li>
                        <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                        </li>
                    {% endif %}
                    {% if profile.personal_website %} 
                        <li>
                        <a title="Personal Website" href="{{ profile.personal_website }}" target="_blank"><i class="im im-globe"></i></a>
                        </li>
                    {% endif %}
                </ul>
                {% if request.user.profile.id != profile.id %}
                    <a href="{% url "send_message" profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
                {% endif %}
                </div>
            </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    {% if profile.bio %}
                        <p class="devInfo__about">
                        {{ profile.bio|linebreaks }}
                        </p>
                    {% endif %}
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Skills</h3>
                    <div class="devInfo__skills">
                        {% for skill in main_skills %}
                            <div class="devSkill">
                                <h4 class="devSkill__title">{{ skill }}</h4>
                                <p class="devSkill__info">
                                {{ skill.description }}
                                </p>
                            </div>
                        {% endfor %}

                        <h3 class="devInfo__subtitle">Other Skills</h3>
                        <div class="devInfo__otherSkills">
                            {% for skill in other_skills %}
                                <span class="tag tag--pill tag--sub tag--lg">
                                    <small>{{ skill }}</small>
                                </span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Projects</h3>
                    <div class="grid grid--two">
                        {% for project in profile.project_set.all %}
                            {% if project.get_image_url %}
                                <div class="column">
                                        <div class="card project">
                                            <a href="{% url "single_project" project.id %}" class="project">
                                                <img class="project__thumbnail" src="{{ project.get_image_url }}" alt="project thumbnail" />
                                                <div class="card__body">
                                                    <h3 class="project__title">{{ project.title }}</h3>
                                                    <p><a class="project__author" href="{% url 'user_profile' profile.id %}">By {{ profile.name }}</a></p>
                                                    <p class="project--rating">
                                                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                                                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
                                                    </p>
                                                    <div class="project__tags">
                                                        {% for tag in project.tags.all %}
                                                            <span class="tag tag--pill tag--main">
                                                                <small>{{ tag }}</small>
                                                            </span>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}